server:
  port: 8880
eureka:
  client:
    service-url:
      defaultZone: http://user:${REGISTRY_SERVER_PASSWORD:123456}@localhost:8761/eureka/
spring:
  cloud:
    config:
      server:
        git:  #git Public warehouse can not fill in the username and password, private warehouse needs to fill in
          uri: https://github.com/sdisk/spring-cloud-project
          search-paths: config-repo
          #username:
          #password:
      label: master
    bus:
      enabled: true  #open spring cloud bus
      trace:
        enabled: true
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest

management:
  endpoints:
    web:
      exposure:
        include: bus-refresh








