eureka:
  client:
    service-url:
      defaultZone: http://user:${REGISTRY_SERVER_PASSWORD:123456}@localhost:8761/eureka/

spring:
  rabbitmq:
    host: 127.0.0.1

logging:
  level:
    com.netflix.discovery.shared.resolver.aws.ConfigClusterResolver: warn