server:
  port: 8762
eureka:
#  instance:
#    prefer-ip-address: true
#    instance-id: ${spring.cloud.client.ip-address}:8761
#    #\u5B9A\u4E49\u5143\u6570\u636E
#    metadata-map:
#      user.name: ${security.user.name}
#      user.password: ${security.user.password}
  client:
    service-url:
      defaultZone: http://user:${REGISTRY_SERVER_PASSWORD:123456}@localhost:8761/eureka/

