server:
  port: 8768
eureka:
  client:
    service-url:
      defaultZone: http://user:${REGISTRY_SERVER_PASSWORD:123456}@localhost:8761/eureka/
spring:
  profiles:
    active: ping_route
---
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false #auto pull service from Eureka
          lower-case-service-id: true
      routes:
        - id: header_route
          uri: http://httpbin.org:80/get
          predicates:
          - Header=X-Request-Id, \d+  # header name value regex
        - id: after_route
          uri: http://localhost:${server.port}/test
          filters:
          - RequestTime=true
          - name: RequestRateLimiter
            args:
              key-resolver: '#{@uriKeyResolver}'
              redis-rate-limiter.replenishRate: 5
              redis-rate-limiter.burstCapacity: 10
          predicates:
          - After=2019-11-13T11:10:17.789-07:00[America/Denver] # time : before, after, between
        - id: cookie_route
          uri: http://httpbin.org:80/get
          predicates:
          - Cookie=name, huang
        - id: ping_route
          uri: lb://ping-balanced-service
          predicates:
            - Path=/gateway/**
          filters:
            - StripPrefix=1
  redis:
    host: localhost
    port: 6379
logging:
  level:
    org.springframework.cloud.gateway: debug
# 禁用 eureka,自己配置
ribbon:
  eureka:
    enabled: false
ping-balanced-service:
  ribbon:
    listOfServers: localhost:8762, localhost:8763
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RoundRobinRule
    NFLoadBalancerPingClassName: com.hq.gateway.ping.HealthMonitor


