server:
  port: 8768
eureka:
  client:
    service-url:
      defaultZone: http://user:${REGISTRY_SERVER_PASSWORD:123456}@localhost:8761/eureka/
spring:
  profiles:
    active: cookie_route
---
spring:
  cloud:
    gateway:
      routes:
        - id: header_route
          uri: http://httpbin.org:80/get
          predicates:
          - Header=X-Request-Id, \d+  # header name value regex
        - id: after_route
          uri: http://localhost:${server.port}/test
          filters:
          - RequestTime=true
          - name: RequestRateLimiter
            args:
              key-resolver: '#{@uriKeyResolver}'
              redis-rate-limiter.replenishRate: 5
              redis-rate-limiter.burstCapacity: 10
          predicates:
          - After=2019-11-03T11:10:17.789-07:00[America/Denver] # time : before, after, between
        - id: cookie_route
          uri: http://httpbin.org:80/get
          predicates:
          - Cookie=name, huang
  profiles: cookie_route
  redis:
    host: localhost
    port: 6379




