server:
  port: 8766
eureka:
  client:
    service-url:
      defaultZone: http://user:${REGISTRY_SERVER_PASSWORD:123456}@localhost:8761/eureka/
zuul:
  host:
    connect-timeout-millis: 15000 #HTTP连接超时大于Hystrix的超时时间
    socket-timeout-millis: 50000 #socket超时
  routes:
    api-v1:
      path: /api-v1/**
      serviceId: ribbon
    api-v2:
      path: /api-v2/**
      serviceId: feign
ribbon:  #设置ribbon的超时时间小于zuul的超时时间
  ConnectTimeout: 10000
  ReadTimeout: 10000





