server:
  port: 8765
eureka:
  client:
    service-url:
      defaultZone: http://user:${REGISTRY_SERVER_PASSWORD:123456}@localhost:8761/eureka/

feign:
  hystrix:
    enabled: true #开启hystrix，默认关闭
  compression:
    request:
      enabled: true
      mime-types:
        - text/xml
        - application/json
      min-request-size: 2048 #压缩的最小阈值，超过则进行压缩
    response:
      enabled: true

#全局配置
#ribbon:
#  ConnectTimeout: 500
#  ReadTimeout: 5000
#指定服务配置
registry-client:
  ribbon:
    #NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
    MaxAutoRetries: 1
    MaxAutoRetriesNextServer: 1
    ConnectTimeout: 500
    ReadTimeOut: 2000
    OkToRetryOnAllOperations: false

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 2001